services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notes_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/notes_db
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://backend:3001
    depends_on:
      - backend
volumes:
  postgres_data:

